from http.client import UNAUTHORIZED
ERROR_CODE_UNAUTHORIZED_USER = 401
ERROR_INCOMPLETE_DATA = 253
     
ERROR_RT_CREATION = "Failed to create a RoundTable"
SUCCESS_MESSAGE = "Success"
SUCCESS_CODE  =200
UNAUTHORIZED_ERROR_MSG = "UnAuthorized User!"
CANNOT_EDIT_RT_MSG = "This RoundTable is already active and cannot be edited now."
NOT_SUPPORTED = "Not Supported"
RT_LOGO_NOT_SUPPORTED = "Logo File Not Supported"
NOT_SUPPORTED_CODE = 256
USER_DATA_NOT_FOUND = "Couldn't Find User data"
ERROR_USER_DATA_NOT_FOUND = 401
ROUNDTABLE_EXPIRED = "RoundTable Expired"
RT_ORG_LOGO = "org_logo"
RT_BRAND_LOGO = "brand_logo"
RT_SUB_BRAND_LOGO = "sub_brand_logo"
MAX_LIMIT_MESSAGE_IMAGE = "Max limit for image 15MB"
MAX_LIMIT_MESSAGE_RT_LOGO_IMAGE = "Max limit for roundtbale image 2MB"
MAX_LIMIT_MESSAGE_DOC = "Max limit for document 15MB"
MAX_LIMIT_MESSAGE_AUDIO = "Max limit for audio 25MB"
MAX_LIMIT_MESSAGE_VIDEO = "Max limit for video 25MB"
RT_NAME_CREATION_MESSAGE = "Please enter a valid name for your RoundTable."
RT_R_TYPE_ERROR_MESSAGE = "Please select the type of RoundTable you want to create."
RT_START_TIME_END_TIME_ERR = "Please enter a start time and end time for your RoundTable."
RT_VISIBILITY_ERROR = "Please select the type of visibility option for your RoundTable."
RT_ANONYMOUS_ERROR = "Please enter either True or False for anonymity."
RT_NOT_FOUND = "Could not find this RoundTable."
RT_DATE_MISSING = "Date field is required"
RT_ID_NOTFOUND = "RoundTable id is not present"
RT_NOT_FOUND_JOIN_ERROR = "Sorry, We couldn't find this RoundTable"
EXCEPTION_ERROR_CODE=255
RT_INVALID_TIME_MSG = "Invalid Time while trying to get this RoundTable"
RT_NOT_STARTED = "RoundTable Not Started"
RT_MOD_NOT_CONFIRMED = "Moderator has not confirmed this RoundTable yet."
RT_NOT_ALLOWED_MSG = "You're not allowed to join this RoundTable."
SERVER_ERROR = "something went wrong!"
SERVER_ERROR_STATUS_CODE = 500
NO_DATA_FOUND = "No data found"
EXCEPTION_ERROR = "Something went wrong"

SHARE_RT_ERROR_MSG = "Trouble Processing this request"
RT_OVER = 'This Roundtable is already over.'
RT_DETAILS_NOT_FOUND = "Could not find details of this RoundTable."
RT_CANCELLED_MSG = "This RoundTable is cancelled."
REGECTED_ERROR_MSG = "You have rejected the invitation to join this RoundTable."
MOD_DATA_NOT_FOUND = "Moderator data not found"
RT_REJECTED_MSG = "You have rejected the invitation to join this RoundTable."
RT_NOT_CONFIRMED = "Roundtable not Confirmed"
RT_DELETED = "Roundtable deleted"
RT_STARTED = 'RoundTable started'